### ISSUE TITLE
AzureAppConfigurationProvider documentation on spec.connectionStringReference

### ISSUE THREAD

**Issue by lwu-st** [Azure/AppConfiguration-KubernetesProvider#102]
Hi,

I'm provisioning this provider with terraform and I plan on using the connectionStringReference to authenticate, but I'm looking to clarify what this parameter is expecting.

Here's my standard `helm_release`:
```
resource "helm_release" "appconfig_kubernetes_provider" {
  name      = "azureappconfiguration.kubernetesprovider"
  version   = "2.2.1"
  namespace = "kube-system"

  chart = "oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider"

  set {
    name = "configMap.name"
    value = "azureConfigMap"
  }
}
```

Now I want to configure the connection string secret for the CRD, but I'm not sure what key it's expecting.
```
resource "kubernetes_secret" "app_config_cstr" {
  metadata {
    name      = "az-app-config-endpoint"
    namespace = "kube-system"
  }

  data = {
    key_name = azurerm_app_configuration.appconfig.primary_read_key.0.connection_string
  }
}
```

Can the team please clarify on what the secret key should be, and if this deployment process looks correct?
Thanks!

**Comment by lwu-st** [comment]
Thank you! That's exactly what I was looking for. Would you also be able to advise on whether this deployment would work?

Installing the helm chart, with an extra `appConfig.connectionStringReference` so I can reference it later in the CRD.
```
resource "helm_release" "appconfig_kubernetes_provider" {
  name      = "azureappconfiguration.kubernetesprovider"
  version   = "2.2.1"
  namespace = "kube-system"

  chart = "oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider"

  set {
    name = "configMap.name"
    value = var.config_map_name
  }

  set {
    name = "appConfig.connectionStringReference"
    value = "azure-app-configuration-connection-string"
  }
}

```

CRD:
```
apiVersion: azconfig.io/v1beta1
kind: AzureAppConfigurationProvider
metadata:
  name: app-config-k8s-provider
  namespace: kube-system
spec:
  connectionStringReference: {{ .Values.appConfig.connectionStringReference }}
  target:
    configMapName: {{ .Values.configMap.name }}
```

**Comment by RichardChen820** [comment]
I'm not very familiar with Terraform, but looks like in your second deployment, you miss to create a secret that contains the connection string, this resource is required:
```
resource "kubernetes_secret" "app_config_cstr" {
  metadata {
    name      = "az-app-config-endpoint"
    namespace = "kube-system"
  }

  data = {
    azure_app_configuration_connection_string = azurerm_app_configuration.appconfig.primary_read_key.0.connection_string
  }
}
```

and in the CRD, the connectionStringReference name could be hardcode, which is the name of the secret you created `az-app-config-endpoint` (It's probably not a good name, `az-app-config-access-secret` sounds better)

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: app-config-k8s-provider
  namespace: kube-system
spec:
  connectionStringReference: az-app-config-endpoint
  target:
    configMapName: {{ .Values.configMap.name }}
```

Note: the apiVersion is `azconfig.io/v1`.
