### ISSUE TITLE
App Configuration Secret names which use colon ":" as separator

### ISSUE THREAD

**Issue by vaganovk** [Azure/AppConfiguration-KubernetesProvider#111]
The problem described below was originally posted under this issue: https://github.com/Azure/AppConfiguration-KubernetesProvider/issues/18 but I assume closed issues are not monitored, so reposting this as new one:

> Faced same issue, where secrets defined in App Configuration in hierarchical format with colon as separator (e.g. "Section:SecretName") cannot be handled by AKS App Configuration provider. 
> 
> Is there any workaround except to rename all App Configuration keys (both settings and secrets - as we want to keep related configuration grouped)? We are currently consuming same App Configuration by .NET services directly and ":" is convenient delimiter to stay with. 
> 
> Are there any other workarounds? 
> 
> The improvement https://github.com/Azure/AppConfiguration/issues/870 seem to be addressing this limitation, but details and timeline is not clear.

Apparently there's simple solution requiring small improvement in AppConfig k8s provider:
1. ASP.NET Core's AddKeyPerFile() configuration provider natively reads k8s secret files and replaces "__" in file name with ":", see https://github.com/dotnet/aspnetcore/blob/c7415ff0ea8999233c6b3272f6edaf772de910ed/src/Configuration.KeyPerFile/src/KeyPerFileConfigurationSource.cs#L57
2. If AKS App Configuration provider could have an option to replace ":" with "__" in secret name, the App Configuration secret ("Section:SecretName") becomes valid k8s secret ("Section__SecretName"). Then, thanks to replacing done by KeyPerFile provider, secret will appear as original "Section:SecretName" to application.

Is it feasible to request such improvement?

**Comment by juniwang** [comment]
https://github.com/Azure/AppConfiguration/issues/870 seems to be the right solution, let's re-prioritize the task

**Comment by RichardChen820** [comment]
This is indeed a limitation of using secrets. We should've addressed it earlier.

Providing an option to replace “:`” with “__” can certainly solve the issue you're facing now, but to me, that feels more like a workaround tailored specifically for .NET users. I’d prefer to implement a solution that addresses the problem more broadly, rather than something that only benefits users of a particular language.

Putting aside implementation complexity for a moment—would you also agree that file-style secrets are a solid solution to this problem?

**Comment by vaganovk** [comment]
@RichardChen820 - I agree it's more a workaround for .NET users, who "by default" is stick to ":" character as delimiter ... or, to anyone else who have picked colon as separator. 

(Colon is "default" format suggested in documentation https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value#keys regardless of language, and in most examples. Of course with a note that users may pick any other delimiter :))

On second point: while in .NET we can consume secrets also as JSON or any other supported format, the file-style secrets seem to be native to k8s and not language dependent - so look like right choice.

Btw, the .NET App Configuration libs provide [Map()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.azureappconfigurationoptions.map?view=azure-dotnet#microsoft-extensions-configuration-azureappconfiguration-azureappconfigurationoptions-map(system-func((azure-data-appconfiguration-configurationsetting-system-threading-tasks-valuetask((azure-data-appconfiguration-configurationsetting)))))) method for users to do mapping for settings read from AppConfiguration - clearly it's not an expectation to get same logic in k8s provider, but at least some ground where adaptation may be helpful.

Thanks!

**Comment by RichardChen820** [comment]
@vaganovk - Indeed, since colon is the default separator used in .NET configuration to represent hierarchical structures, the vast majority of .NET users rely on it. we recommend using colon in our documentation is also since most of our users are .NET developers.

Reading configuration from structured files is a common practice across all programming languages, and .NET has also been [optimized](https://learn.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-9.0#dotnet-watch-configuration) for watching file changes in Kubernetes (container) scenarios.

**Comment by RichardChen820** [comment]
Could you  explain this more?
> clearly it's not an expectation to get same logic in k8s provider, but at least some ground where adaptation may be helpful.

**Comment by vaganovk** [comment]
Was trying to say: the presence of Map() method in .NET App Configuration library indicates that sometimes there's a need for transformation to be applied on client side (after settings were read from API and before they're applied to configuration). 

App Configuration k8s Provider does not have to support every possible transformation, but possibly could have some (like ":" ==> "__") if it addresses a common problem for users.

**Comment by RichardChen820** [comment]
The new v2.3.0 supports constructing secret data into json, yaml or properties type like what configMap has, you can use it in this way:

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: <your-app-configuration-store-endpoint>
  target:
    configMapName: configmap-created-by-appconfig-provider
  secret:
    target:
      secretName: secret-created-by-appconfig-provider
      secretData:
        key: secret.json
        separator:  ":"
        type: json
```

**Comment by RichardChen820** [comment]
And it also supports dynamic configuration, you consume the secret as mounted file:
```
builder.Configuration.AddJsonFile("config/mysettings.json", reloadOnChange: true, optional: false);
```
And set the env var `DOTNET_USE_POLLING_FILE_WATCHER` to true, your app will hot load the lastest data from Azure App Configuraiton without restarting.

**Comment by linglingye001** [comment]
Hi @kimpenhaus , there are two ways to mount ConfigMaps:

- As volume mounts - Updates are propagated (with some delay)
- As subPath mounts - Updates are NOT propagated

To get dynamic configuration working:

- Mount the entire ConfigMap volume (not using subPath):

```
    spec:
      containers:
      - name: aspnetapp
        image: myregistry.azurecr.io/aspnetapp:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume 
        configMap: 
          name: configmap-created-by-appconfig-provider
```

- Reference the full path in your .NET configuration:

`builder.Configuration.AddJsonFile("config/secret.json", reloadOnChange: true, optional: false);`

- Set polling environment variable:

```
env:
- name: DOTNET_USE_POLLING_FILE_WATCHER
  value: "true"
```

This way, when the Azure App Configuration Provider updates the ConfigMap, Kubernetes will update the mounted files, and .NET's file watcher will detect the changes. You can refer to this [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/enable-dynamic-configuration-azure-kubernetes-service) for more information about dynamic refresh. Thanks

**Comment by vaganovk** [comment]
@RichardChen820 had a chance to verify new functionality with 
```
secretData:
        key: secret.json
        separator:  ":"
        type: json
```
Works like a charm - will migrate from KeyPerFile provider as it will allow us to have old good ":" as delimiter in App Configuration for both akv secrets and non-secret parameters. 

Thank you!
