### ISSUE TITLE
Error creating config map

### ISSUE THREAD

**Issue by ShortMVitesse** [Azure/AppConfiguration-KubernetesProvider#19]
we've deployed this provider but are struggling to get it working. 

we get the following error in the pod logs. 

```
Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider 'appconfig-portal-insights' in 'vnext' namespace: ManagedIdentityCredential: ManagedIdentityCredential: Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=f0ad9467-979b-4fa0-9235-3798532c828b&resource=https%3A%2F%2Ftst-uks-appconf.azconfig.io": context deadline exceeded 
```

which reads like an issue with the AIMS instance in the node. anyone seen this before?

**Comment by RichardChen820** [comment]
What it AIMS account for? Looks like you are using managed identity, could you share the yaml you are using?

**Comment by ShortMVitesse** [comment]
im sure you know this better than me, but just in case. AIMS = Azure Instance Metadata Service and its the miniature website hosted on the 169 address in the error.  http://169.254.169.254/metadata/identity/oauth2/token

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfig-portal-insights
  namespace: vnext
spec:
  endpoint: https://blah-blah-appconf.azconfig.io
  target:
    configMapName: configmap-portal-insights
    configMapData: 
      type: json
      key: mysettings.json  
  auth:
    managedIdentityClientId: f0ad9467-1234-4fa0-9235-3798532c828b
  configuration:
    selectors:
      - keyFilter: '*'
        labelFilter: service-portal-insights
```

**Comment by RichardChen820** [comment]
I'm not able to reproduce the issue on my side, have you enabled pod-managed identity or wokload identity on your cluster?

**Comment by ShortMVitesse** [comment]
we're not ready to enable workload identity yet, so we have to get this working with the managed identity for now.

**Comment by RichardChen820** [comment]
Do you mind re-installing it with more detailed log verbosity to see if it could help with root cause the issue?

```
helm install azureappconfiguration.kubernetesprovider \
     oci://mcr.microsoft.com/azure-app-configuration/helmchart/kubernetes-provider \
     --namespace azappconfig-system \
     --create-namespace \
     --set logVerbosity=5
```

**Comment by ShortMVitesse** [comment]
would love to. can you help me find the reference for a helm chart to deploy it, as thats how we do it. not sure where to pass that log level in a helm chart. 

```
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-app-configuration
  namespace: azappconfig-system
spec:
  releaseName: azure-app-configuration
  chart:
    spec:
      chart: kubernetes-provider
      sourceRef:
        name: azure-app-configuration
        kind: HelmRepository
        namespace: flux-system
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
logverbosity: 3
```

**Comment by RichardChen820** [comment]
Could you try:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-app-configuration
  namespace: azappconfig-system
spec:
  releaseName: azure-app-configuration
  chart:
    spec:
      chart: kubernetes-provider
      sourceRef:
        name: azure-app-configuration
        kind: HelmRepository
        namespace: flux-system
  interval: 10m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
   values:
      logverbosity: 3

```
