### ISSUE TITLE
Error creating configmap with Workload Identity

### ISSUE THREAD

**Issue by eokorieFA** [Azure/AppConfiguration-KubernetesProvider#23]
I am struggling to get this feature working with Azure Workload Identity.  I have an application that has been deployed into the cluster.  The application already had a Workload Identity which it currently uses to fetch secrets from an Azure Keyvault and I can confirm this is working as intended.  The identity has also been granted the role "App Configuration Data Reader".

However, when trying to get the App Configuration feature working, I am getting the following error:

```
Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider 'laravelapp-app-config' in 'laravelapp' namespace: no token file specified. Check pod configuration or set TokenFilePath in the options
```

I am making use of Terraform for the work I am doing and I also set the log versbosity to 3:
```
resource "kubernetes_namespace" "azure-app-config" {
  count = var.enable_aac ? 1 : 0
  metadata {
    name   = "azappconfig-system"
    labels = {
      deployed-by = "Terraform"
    }
  }
}

resource "helm_release" "azure-app-config" {
  count      = var.enable_aac ? 1 : 0
  name       = "azureappconfiguration.kubernetesprovider"
  repository = "oci://mcr.microsoft.com/azure-app-configuration/helmchart"
  chart      = "kubernetes-provider"
  namespace  = kubernetes_namespace.azure-app-config[0].metadata.0.name

  version = "1.2.0"

  timeout = 1800

  depends_on = [
    azurerm_kubernetes_cluster.k8s
  ]

  set {
    name = "env.azureClientId"
    value = var.azure_clientId
  }

  set {
    name = "env.azureTenantId"
    value = var.azure_tenantId
  }

  set {
    name = "logVerbosity"
    value = 3
  }

  values = [ <<-EOT
    nodeSelector:
      kubernetes.io/os: linux
  EOT
  ]
}
```

The above successfully installs the provider in the cluster. I also deploy my application using a helm chart, so I create a yaml file with for the application that I am working with, which looks like this:

```
{{- if .Values.azureAppConfiguration.enabled }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "laravelapp.fullname" . }}-app-config
  labels:
    {{- include "laravelapp.labels" . | nindent 4 }}
spec:
  endpoint: {{ .Values.azureAppConfiguration.storeEndpoint }}
  target:
    configMapName: configmap-app-configuration
#   keyValues:
#     selectors:
#       - keyFilter: Settings:*
#     keyVaults:
#       target:
#         secretName: my-secrets
  auth:
    workloadIdentity:
      managedIdentityClientId: {{ .Values.secretProviderClass.clientID }}
{{- end }}
```

The deployment.yaml file has been has had the following added:
```
spec:
  volumes:
    - name: app-config-volume
      configMap:
         name: configmap-app-configuration
 containers:
   - name: laravelapp
     volumeMounts:
       - name: app-config-volume
         mountPath: /app/config
```

However, upon deployment, I am getting a couple of issues:
<img width="1508" alt="Screenshot 2024-03-14 at 11 36 02" src="https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/69154958-63f7-429b-8a9c-884eaa53de01">

The configmap does not get created

<img width="1508" alt="Screenshot 2024-03-14 at 11 36 57" src="https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/75e10f71-f165-42e6-a157-28e3eda0cd4e">

The app config volume refuses to be mounted.

Any help will be appreciated.

Thank you...

**Comment by linglingye001** [comment]
Hi @eokorieFA, have you created the federated identity credential of the workload managed identity? You can find more information about how to [use workload identity](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#use-workload-identity) in k8s provider reference doc. Please let me know if you have any further questions or encounter any issues. Thanks.

**Comment by eokorieFA** [comment]
hi @linglingye001,

I can confirm that the federated identity for the workload identity has been created.  When checking the cluster and generated yaml for the laravel-app-config, I can see it has been pulled into the cluster.

<img width="1508" alt="Screenshot 2024-03-14 at 13 20 53" src="https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/991c6bfb-e7ba-4e29-abb3-dc40ed0ca8f2">

The same idenity  is being used to access Azure Keyvault secrets and the secrets are being pulled in with no issues...

**Comment by RichardChen820** [comment]
The error indicates the running pod can't find the federated token file that is supposed to be mounted. I believe you have confirmed that the workload identity is enabled on this cluster. Do you mind check and share the labels of the running appconfig provider deployment? It should has a label `azure.workload.identity/use: "true"`

**Comment by eokorieFA** [comment]
hi @RichardChen820,

I can confirm that label is there...

![Screenshot 2024-03-15 at 07 45 33](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/7afaead8-a168-4700-b45f-b1a8dce575b3)
The deployment has the label

![Screenshot 2024-03-15 at 07 46 02](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/475edd75-6f41-4d1a-96c7-9a6a298d3a86)
The pod has the label

![Screenshot 2024-03-15 at 07 46 23](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/584e4fb8-b136-4ef2-b2d4-d5966e4b08ef)
The service account has the label... However, ```
azure.workload.identity/client-id=``` is empty...  Could this be the issue?  Does the appconfig provider need a separate workload identity from the applications?

**Comment by RichardChen820** [comment]
Do you mind double check the workloadIdentity status of your cluster?

```
az aks show  -g <your-cluster-resource-group> -n <your-cluster-name> --query "securityProfile"
```

From my end with workloadIdentity enabled, it shows:
<img width="788" alt="image" src="https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/99175581/8b69c3f8-be8b-4752-ad2d-3d975f931eff">

**Comment by RichardChen820** [comment]
And should see such an env variable being set to your running pod of app config provider controller.
<img width="541" alt="image" src="https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/99175581/7392b787-642f-4b56-8bac-16e6c20196f8">

**Comment by eokorieFA** [comment]
This is what I have:
![Screenshot 2024-03-15 at 18 16 04](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/44394920/90799fdd-9d64-4aaf-a1d8-3feea85fdb9c)


There is also an AZURE_FEDERATED_TOKEN_FILE env variable that has been set...

**Comment by RichardChen1122** [comment]
This is indeed bizarre, this is where it throws the error. https://github.com/Azure/azure-sdk-for-go/blob/9b1d280f052510a0de6764582ba2766b3cf7c449/sdk/azidentity/workload_identity.go#L72

You've confirmed `AZURE_FEDERATED_TOKEN_FILE` env variable has been set, I'm a bit lost

**Comment by eokorieFA** [comment]
@RichardChen1122 I changed a couple of things... I am not however getting:

```Fail to create the target ConfigMap or Secret of AzureAppConfigurationProvider 'laravelapp-app-config' in 'laravelapp' namespace: invalid resource name "https://appconfigstore-example.azconfig.io": [may not contain '/']```

I feel this is getting close to being resolved :-)

**Comment by RichardChen820** [comment]
Are you using `connectionStringReference` field now? Most likely you are using such a yaml:

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  connectionStringReference: https://appconfigstore-example.azconfig.io  #This line is not right.
  target:
    configMapName: configmap-created-by-appconfig-provider
```

The `connectionStringReference` must be populated with the name of a Secret which contains the connectionString of the target app config store.
Please see [here](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#use-connection-string) for the detail of using connection string

**Comment by RichardChen820** [comment]
To make connection string work, you should:
1. Create a Secret with connectionString of target app config store
```
kubectl create secret generic appconfig-secret --from-literal azure_app_configuration_connection_string=<read-only connection string of target app config store> -n <same namespace of azureappconfigurationprovider resource>
```
2. Set the name of created secret to the AzureAppConfigurationProvder yaml
```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
   namespace: <your namespace>
spec:
  connectionStringReference: appconfig-secret
  target:
    configMapName: configmap-created-by-appconfig-provider
```
