### ISSUE TITLE
Partial Configuration data in the ConfigMap / Missing Feature Manager data

### ISSUE THREAD

**Issue by nosalan** [Azure/AppConfiguration-KubernetesProvider#38]
## Problem description 
In my Azure App Configuration I have 2 configuration entries and 1 feature flag. However, I can only see 1 configuration entry in the Config Map created by the Azure App Configuration Kubernetes Provider. Deleting the Config Map doesn't help.

## Steps to reproduce

1. Here is the content of Azure App Configuration / Configuration Explorer:

![image](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/2273250/fd6007be-eabd-4608-8276-727e757f490a)

2. Here is the content of Azure App Configuration / Feature Manager:

![image](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/2273250/ab39473d-a178-4ede-9c06-6a25deda575d)
in details:
![image](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/2273250/dc29da3a-6b44-47d4-b1c1-da41c659070b)

3.  CRD Definition

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  annotations:
    meta.helm.sh/release-name: test-app
    meta.helm.sh/release-namespace: test-app
  labels:
    app.kubernetes.io/managed-by: Helm
  name: appconfigurationprovider-sample
  namespace: test-app
spec:
  auth:
    workloadIdentity:
      managedIdentityClientId: <REDACTED>
  configuration:
    selectors:
    - keyFilter: '*'
  endpoint: https://<REDACTED>.azconfig.io
  featureFlag:
    refresh:
      enabled: true
      interval: 30s
    selectors:
    - keyFilter: '*'
  replicaDiscoveryEnabled: true
  target:
    configMapData:
      key: mysettings.json
      type: json
    configMapName: configmap-created-by-appconfig-provider
```

5. Actual config map content (view yaml). **The problem is that the data contains only the aaaa config entry and not the 
tenant2/conf-key1** Also there is no feature flag data.

```
apiVersion: v1
data:
  mysettings.json: '{"aaaa":"bbbb","feature_management":{"feature_flags":[]}}'
kind: ConfigMap
metadata:
  annotations:
    azconfig.io/LastReconcileTime: 2024-04-26 15:44:28.861791156 +0000 UTC
    meta.helm.sh/release-name: test-app
    meta.helm.sh/release-namespace: test-app
  creationTimestamp: "2024-04-26T15:31:58Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: configmap-created-by-appconfig-provider
  namespace: test-app
  ownerReferences:
  - apiVersion: azconfig.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: AzureAppConfigurationProvider
    name: appconfigurationprovider-sample
    uid: 4868699d-760a-4949-a756-6d244a267f23
  resourceVersion: "12206612"
  uid: 5963d8c2-0f03-44f4-9c3c-79cac09d0c85
```

## Additional information

Version: `kubernetes-provider:1.3.1`
Describe CRD output (Status):
![image](https://github.com/Azure/AppConfiguration-KubernetesProvider/assets/2273250/7e731111-1c0e-4691-b4c3-c04f366d3e9a)

**Comment by RichardChen820** [comment]
@nosalan  If the `labelFilter` is absent in the selectors, the kay-values/featureFalgs with `no label` are selected. You didn't see `tenant2/conf-key1` since its label is `xda`, the same for feature flag.

You just need to specify the label in selector:

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  annotations:
    meta.helm.sh/release-name: test-app
    meta.helm.sh/release-namespace: test-app
  labels:
    app.kubernetes.io/managed-by: Helm
  name: appconfigurationprovider-sample
  namespace: test-app
spec:
  auth:
    workloadIdentity:
      managedIdentityClientId: <REDACTED>
  configuration:
    selectors:
    - keyFilter: '*'
    - keyFilter: '*'
       labelFilter: xda
  endpoint: https://<REDACTED>.azconfig.io
  featureFlag:
    refresh:
      enabled: true
      interval: 30s
    selectors:
    - keyFilter: '*'
       labelFilter: 'my -lab'
  replicaDiscoveryEnabled: true
  target:
    configMapData:
      key: mysettings.json
      type: json
    configMapName: configmap-created-by-appconfig-provider
```

**Comment by nosalan** [comment]
Thanks for suggestion @RichardChen820 I need to download all settings regardless of label, so this is what I tried. But it still doesn't work.
```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: https://<REDACTED>.azconfig.io
  configuration:
    selectors:
      - keyFilter: "*"
        labelFilter: "*"

  featureFlag:
    selectors:
      - keyFilter: '*'
        labelFilter: "*"
    refresh:
      enabled: true

  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData:
      type: json
      key: mysettings.json
  auth:
    workloadIdentity:
      managedIdentityClientId: <REDACTED>

```
