### ISSUE TITLE
Unable to refresh keys automatically without using sentinel

### ISSUE THREAD

**Issue by nosalan** [Azure/AppConfiguration-KubernetesProvider#40]
I have problem with receiving updates made in a Configuration Explorer. I don't want to use sentinel keys, I would like my provider to consume updates to all configuration values but the Config Map is not refreshed upon adding and updating configuration settings.
I tried specifying something like this but the error is: `spec.configuration.refresh.monitoring: Required value`
```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
  name: <REDACTED>
  namespace: demo
spec:
  auth:
    workloadIdentity:
      managedIdentityClientId: <REDACTED>
  configuration:
    refresh:
      enabled: true
      interval: 30s
    selectors:
    - keyFilter: '*'
```

The [documentation](https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider?tabs=default#configuration-refresh) says that `you can use a key-value to signal the completion of your update. This key-value is known as the sentinel key. ` Seems that it's something that you **must** use in order to consume the updates of all keys, not something you can use. Am I correct?

I expected the functionality to download updates to all configuration keys and their updates as the fundamental functionality of the provider but maybe I'm doing something wrong.
