### ISSUE TITLE
Key Vault Secret references are not loaded

### ISSUE THREAD

**Issue by tobiasholzner-whiteduck** [Azure/AppConfiguration-KubernetesProvider#67]
I want to load configuration settings and key vault references into Kubernetes ConfigMaps and Secrets. The configuration settings are successfully loaded into the Kubernetes ConfigMap, but the Secrets are not being populated with data. Although the Secret is created, it remains empty.

used version: tried with 1.3.1 and 2.0.0-preview

I use the following manifest: 

```yaml
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: myapp-backend
  namespace: myapp
spec:
  auth:
    workloadIdentity:
      managedIdentityClientId: XXXXXXXXXXXXXXXXXXXX
  endpoint: https://myapp.azconfig.io
  secret:
    target:
      secretName: myapp-backend-secret
    auth:
      workloadIdentity:
        managedIdentityClientId: XXXXXXXXXXXXXXXXXXXXXXXX
  target:
    configMapName: myapp-backend-appconfig
```

There are no error logs in the az-appconfig-k8s-provider pod

**Comment by RichardChen820** [comment]
@tobiasholzner-whiteduck Have you checked this FAQ? Although it refers to the configMap, the scene for secrets is actually the same.

**Comment by zhenlan** [comment]
Sounds like a bug according to the doc:

https://learn.microsoft.com/en-us/azure/azure-app-configuration/reference-kubernetes-provider
_If the spec.configuration.selectors property isn't set, all key-values with no label are downloaded._

**Comment by RichardChen820** [comment]
@zhenlan Right, it's a bug scenario, in other providers, `labelFilter=string.empty` and `labelFilter=null` are equivalent.

**Comment by RichardChen820** [comment]
@tobiasholzner-whiteduck  I would not suggest you to use this keyFilter/labelFilter pair to select the keyvault references.

```
configuration:
    selectors:
      - keyFilter: '*'
        labelFilter: ''
```

Although it now works for you, it should not behave in this way. Please specify the desired label of your keyvault references you want to select.
