### ISSUE TITLE
Multi Key Value Secret support

### ISSUE THREAD

**Issue by spintower** [Azure/AppConfiguration-KubernetesProvider#82]
Does AppConfiguration-KubernetesProvider support multi-key-value secrets similar to https://akv2k8s.io/tutorials/sync/4-multi-key-value-secret/ and https://external-secrets.io/latest/guides/all-keys-one-secret/?

**Comment by RichardChen820** [comment]
@spintower  Short answer is yes.

Secrets resolved from keyVault references are saved into the `Secret` you specify in the `AzureAppConfigurationProvider` yaml:

```
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: appconfigurationprovider-sample
spec:
  endpoint: <your-app-configuration-store-endpoint>
  target:
    configMapName: my-configmap
  configuration:
    selectors:
      - keyFilter: app1*
  secret:
    target:
      secretName: my-secret
    auth:
      managedIdentityClientId: <your-user-assigned-managed-identity-client-id>
```

Use above yaml as an example, all the selected keyVault reference items will be saved into `my-secret`, use the AppConfig item‘s key as the key, and the value of the referenced KeyVault secret as the value.
